### ISSUE TITLE
YAML (yml), JSON or XML support for hierachical site properties

### ISSUE THREAD

**Issue by ge0ffrey** [jbake-org/jbake#680]
When migrating optaplanner.org from Awestruct to hopefully JBake, I 'd like to keep an `events.yml` file (or .json or .xml) with this a list of all events which should be displayed as html on every page after running through a freemarker template:
```
- eventId: 20180508-redhatsummit
  eventOrganization: "Red Hat Summit"
  eventUrl: https://www.redhat.com/en/summit/2018
  location: San Francisco, CA, USA
  date: 2018-05-08
  talks:
    - title: "Employee shift rostering optimization A.I. with OptaPlanner"
      url: https://agenda.summit.redhat.com/SessionDetail.aspx?id=154183
      presenters: Geoffrey De Smet, Christopher Chianelli
    - title: "Consulting Discovery Zone - Constraint Optimizer: \"I bet you I'm better than a human\""
      url: https://agenda.summit.redhat.com/SessionDetail.aspx?id=176035
      presenters: Justin Goldsmith, Christian Witchger

- eventId: 20210415-soujavamotu
  eventOrganization: "SouJava MOTU"
  location: Worldwide
  date: 2021-04-15
  talks:
    - title: "Planejamento de Recursos com OptaPlanner"
      url: https://www.meetup.com/SouJava/events/275951378/
      presenters: Karina Varela, Otávio Santana

- eventId: 20210423-viaboxx
  eventOrganization: "Red Hat Germany"
  location: Germany
  date: 2021-04-23
  talks:
    - title: "Optimierung des Field Service Management mit Hilfe von Constraint Solving Algorithmen"
      url: https://events.redhat.com/profile/form/index.cfm?PKformID=0x362692d869
      presenters: Stephan Kraft, Simon Tiffert
```

**This information can't fit into a `*.properties` file because it is hierarchical.** Ideally, JBake supports yml, json or xml for this kind of information too.
